-- MIGRA-Go Test Data: v4 schema evolution
-- Version v4 extends v3 with IDENTITY columns, COLLATE, and FK CASCADE actions.

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL COLLATE "en_US",
    email VARCHAR(100) DEFAULT 'unknown',
    created_at TIMESTAMP DEFAULT now(),
    phone VARCHAR(20),
    UNIQUE (email)
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    sort_order INTEGER DEFAULT 0
);

CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE UNIQUE INDEX idx_users_username_unique ON users(username);

CREATE TYPE user_role AS ENUM ('admin', 'user', 'moderator');
