package diff

import (
	"fmt"

	"github.com/fred29910/migra-go/internal/model"
	"github.com/fred29910/migra-go/internal/util"
)

// AddColumnOp represents an operation to add a new column to an existing table.
type AddColumnOp struct {
	baseOperation
	Schema string
	Table  string
	Column *model.Column
}

// NewAddColumnOp creates a new AddColumnOp.
func NewAddColumnOp(schema, table string, col *model.Column) *AddColumnOp {
	return &AddColumnOp{
		baseOperation: baseOperation{
			kind:      KindAddColumn,
			objectKey: model.NewObjectKey(schema, table+"."+col.Name, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: col,
	}
}

// IsDestructive returns false; adding a column is not a destructive operation.
func (op *AddColumnOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *AddColumnOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// RenderString renders the SQL statement for adding a column.
func (op *AddColumnOp) RenderString(ctx RenderContext) string {
	col := op.Column
	sql := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(col.Name), col.DataType)

	if col.IsIdentity {
		switch col.IdentityKind {
		case "ALWAYS":
			sql += " GENERATED ALWAYS AS IDENTITY"
		case "BY DEFAULT":
			sql += " GENERATED BY DEFAULT AS IDENTITY"
		}
	}

	if col.Collation != "" {
		sql += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(col.Collation))
	}
	if !col.IsNullable {
		sql += " NOT NULL"
	}
	if col.DefaultExpr != nil {
		sql += fmt.Sprintf(" DEFAULT %s", *col.DefaultExpr)
	}

	return fmt.Sprintf("-- op: add_column risk:low\n%s;", sql)
}

// RenderString renders the SQL statement for altering a column type.
func (op *AlterColumnTypeOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column), op.ToType)
	if op.UsingExpr != "" {
		sql += " USING " + op.UsingExpr
	}
	return fmt.Sprintf("-- op: alter_column_type risk:high\n%s;", sql)
}

// RenderString renders the SQL statement for setting a column to NOT NULL.
func (op *SetNotNullOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column))
	return fmt.Sprintf("-- op: set_not_null risk:low\n%s;", sql)
}

// RenderString renders the SQL statement for dropping NOT NULL from a column.
func (op *DropNotNullOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column))
	return fmt.Sprintf("-- op: drop_not_null risk:low\n%s;", sql)
}

// RenderString renders the SQL statement for setting a column default.
func (op *SetDefaultOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: set_default risk:low\nALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.DefaultExpr,
	)
}

// RenderString renders the SQL statement for dropping a column default.
func (op *DropDefaultOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_default risk:low\nALTER TABLE %s ALTER COLUMN %s DROP DEFAULT;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

// RenderString renders the SQL statement for altering a column collation.
func (op *AlterColumnCollationOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DATA TYPE %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.DataType,
	)
	if op.ToCollation != "" {
		sql += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(op.ToCollation))
	}
	return fmt.Sprintf("-- op: alter_column_collation risk:low\n%s;", sql)
}

// RenderString renders the SQL statement for dropping a column.
func (op *DropColumnOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_column risk:high\nALTER TABLE %s DROP COLUMN IF EXISTS %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

// RenderString renders the SQL statement for adding an identity to a column.
func (op *AddIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: add_identity risk:low\nALTER TABLE %s ALTER COLUMN %s ADD GENERATED %s AS IDENTITY;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.IdentityKind,
	)
}

// RenderString renders the SQL statement for setting an identity on a column.
func (op *SetIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: set_identity risk:low\nALTER TABLE %s ALTER COLUMN %s SET GENERATED %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.IdentityKind,
	)
}

// RenderString renders the SQL statement for dropping an identity from a column.
func (op *DropIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_identity risk:medium\nALTER TABLE %s ALTER COLUMN %s DROP IDENTITY;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

// RenderString renders the SQL statement for renaming a column.
func (op *RenameColumnOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: rename_column risk:low\nALTER TABLE %s RENAME COLUMN %s TO %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.OldName),
		util.QuoteIdentifier(op.NewName),
	)
}

// AlterColumnTypeOp represents an operation to change a column's data type.
type AlterColumnTypeOp struct {
	baseOperation
	Schema    string
	Table     string
	Column    string
	FromType  string
	ToType    string
	UsingExpr string
}

// NewAlterColumnTypeOp creates a new AlterColumnTypeOp.
func NewAlterColumnTypeOp(schema, table, column, fromType, toType string) *AlterColumnTypeOp {
	return &AlterColumnTypeOp{
		baseOperation: baseOperation{
			kind:      KindAlterColumnType,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:   schema,
		Table:    table,
		Column:   column,
		FromType: fromType,
		ToType:   toType,
	}
}

// IsDestructive returns true; altering a column type can cause data loss.
func (op *AlterColumnTypeOp) IsDestructive() bool {
	return true
}

// DependsOn returns the object keys this operation depends on.
func (op *AlterColumnTypeOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// SetNotNullOp represents an operation to set a column to NOT NULL.
type SetNotNullOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

// NewSetNotNullOp creates a new SetNotNullOp.
func NewSetNotNullOp(schema, table, column string) *SetNotNullOp {
	return &SetNotNullOp{
		baseOperation: baseOperation{
			kind:      KindSetNotNull,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

// IsDestructive returns false; setting NOT NULL is not destructive.
func (op *SetNotNullOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *SetNotNullOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// DropNotNullOp represents an operation to drop NOT NULL from a column.
type DropNotNullOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

// NewDropNotNullOp creates a new DropNotNullOp.
func NewDropNotNullOp(schema, table, column string) *DropNotNullOp {
	return &DropNotNullOp{
		baseOperation: baseOperation{
			kind:      KindDropNotNull,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

// IsDestructive returns false; dropping NOT NULL is not destructive.
func (op *DropNotNullOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *DropNotNullOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// DropColumnOp represents an operation to drop a column from a table.
type DropColumnOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

// NewDropColumnOp creates a new DropColumnOp.
func NewDropColumnOp(schema, table, column string) *DropColumnOp {
	return &DropColumnOp{
		baseOperation: baseOperation{
			kind:      KindDropColumn,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

// IsDestructive returns true; dropping a column causes data loss.
func (op *DropColumnOp) IsDestructive() bool {
	return true
}

// DependsOn returns the object keys this operation depends on.
func (op *DropColumnOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// SetDefaultOp represents an operation to set a default expression on a column.
type SetDefaultOp struct {
	baseOperation
	Schema      string
	Table       string
	Column      string
	DefaultExpr string
}

// NewSetDefaultOp creates a new SetDefaultOp.
func NewSetDefaultOp(schema, table, column, defaultExpr string) *SetDefaultOp {
	return &SetDefaultOp{
		baseOperation: baseOperation{
			kind:      KindSetDefault,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:      schema,
		Table:       table,
		Column:      column,
		DefaultExpr: defaultExpr,
	}
}

// IsDestructive returns false; setting a default is not destructive.
func (op *SetDefaultOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *SetDefaultOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// DropDefaultOp represents an operation to drop a default expression from a column.
type DropDefaultOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

// NewDropDefaultOp creates a new DropDefaultOp.
func NewDropDefaultOp(schema, table, column string) *DropDefaultOp {
	return &DropDefaultOp{
		baseOperation: baseOperation{
			kind:      KindDropDefault,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

// IsDestructive returns false; dropping a default is not destructive.
func (op *DropDefaultOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *DropDefaultOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// SetIdentityOp represents an operation to set the identity generation option on a column.
type SetIdentityOp struct {
	baseOperation
	Schema       string
	Table        string
	Column       string
	IdentityKind string
}

// NewSetIdentityOp creates a new SetIdentityOp.
func NewSetIdentityOp(schema, table, column, identityKind string) *SetIdentityOp {
	return &SetIdentityOp{
		baseOperation: baseOperation{
			kind:      KindSetIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:       schema,
		Table:        table,
		Column:       column,
		IdentityKind: identityKind,
	}
}

// IsDestructive returns false; setting an identity is not destructive.
func (op *SetIdentityOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *SetIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// DropIdentityOp represents an operation to drop the identity property from a column.
type DropIdentityOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

// NewDropIdentityOp creates a new DropIdentityOp.
func NewDropIdentityOp(schema, table, column string) *DropIdentityOp {
	return &DropIdentityOp{
		baseOperation: baseOperation{
			kind:      KindDropIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

// IsDestructive returns true; dropping an identity can be destructive.
func (op *DropIdentityOp) IsDestructive() bool {
	return true
}

// DependsOn returns the object keys this operation depends on.
func (op *DropIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

// AddIdentityOp represents an operation to add an identity property to an existing column.
type AddIdentityOp struct {
	baseOperation
	Schema       string
	Table        string
	Column       string
	IdentityKind string
}

// NewAddIdentityOp creates a new AddIdentityOp.
func NewAddIdentityOp(schema, table, column, identityKind string) *AddIdentityOp {
	return &AddIdentityOp{
		baseOperation: baseOperation{
			kind:      KindAddIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:       schema,
		Table:        table,
		Column:       column,
		IdentityKind: identityKind,
	}
}

// IsDestructive returns false; adding an identity is not destructive.
func (op *AddIdentityOp) IsDestructive() bool { return false }

// DependsOn returns the object keys this operation depends on.
func (op *AddIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{model.NewObjectKey(op.Schema, op.Table, model.KindTable)}
}

// AlterColumnCollationOp represents an operation to change a column's collation.
type AlterColumnCollationOp struct {
	baseOperation
	Schema        string
	Table         string
	Column        string
	DataType      string
	FromCollation string
	ToCollation   string
}

// NewAlterColumnCollationOp creates a new AlterColumnCollationOp.
func NewAlterColumnCollationOp(schema, table, column, dataType, fromCollation, toCollation string) *AlterColumnCollationOp {
	return &AlterColumnCollationOp{
		baseOperation: baseOperation{
			kind:      KindAlterColumnCollation,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:        schema,
		Table:         table,
		Column:        column,
		DataType:      dataType,
		FromCollation: fromCollation,
		ToCollation:   toCollation,
	}
}

// IsDestructive returns false; altering collation is not destructive.
func (op *AlterColumnCollationOp) IsDestructive() bool {
	return false
}

// DependsOn returns the object keys this operation depends on.
func (op *AlterColumnCollationOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}
