package diff

import (
	"fmt"
	"strings"

	"github.com/fred29910/migra-go/internal/model"
	"github.com/fred29910/migra-go/internal/util"
)

// AddTableOp represents adding a new table
type AddTableOp struct {
	baseOperation
	Table *model.Table
}

// NewAddTableOp creates a new AddTableOp
func NewAddTableOp(schema, name string, table *model.Table) *AddTableOp {
	return &AddTableOp{
		baseOperation: baseOperation{
			kind:      KindAddTable,
			objectKey: model.NewObjectKey(schema, name, model.KindTable),
		},
		Table: table,
	}
}

// RenderString renders the add table operation as SQL.
func (op *AddTableOp) RenderString(ctx RenderContext) string {
	table := op.Table
	lines := make([]string, 0)

	for _, col := range table.Columns {
		colDef := fmt.Sprintf("    %s %s", util.QuoteIdentifier(col.Name), col.DataType)
		if col.IsIdentity {
			switch col.IdentityKind {
			case "ALWAYS":
				colDef += " GENERATED ALWAYS AS IDENTITY"
			case "BY DEFAULT":
				colDef += " GENERATED BY DEFAULT AS IDENTITY"
			}
		}
		if col.Collation != "" {
			colDef += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(col.Collation))
		}
		if !col.IsNullable {
			colDef += " NOT NULL"
		}
		if col.DefaultExpr != nil {
			colDef += fmt.Sprintf(" DEFAULT %s", *col.DefaultExpr)
		}
		lines = append(lines, colDef)
	}

	if table.PrimaryKey != nil {
		pk := &model.Constraint{
			Name:    table.PrimaryKey.Name,
			Type:    "primary_key",
			Columns: table.PrimaryKey.Columns,
		}
		if rendered := renderConstraint(pk); rendered != "" {
			lines = append(lines, "    "+rendered)
		}
	}

	if len(table.Constraints) > 0 {
		names := make([]string, 0, len(table.Constraints))
		for name := range table.Constraints {
			names = append(names, name)
		}
		for _, name := range names {
			c := table.Constraints[name]
			if table.PrimaryKey != nil && c.Name == table.PrimaryKey.Name {
				continue
			}
			if rendered := renderConstraint(c); rendered != "" {
				lines = append(lines, "    "+rendered)
			}
		}
	}

	sql := fmt.Sprintf("-- op: add_table risk:low\nCREATE TABLE %s (\n%s\n);",
		util.QuoteQualifiedIdentifier(table.Schema, table.Name),
		strings.Join(lines, ",\n"))
	return sql
}

// IsDestructive returns false for add table operations
func (op *AddTableOp) IsDestructive() bool {
	return false
}

// DependsOn returns dependencies for add table operations (foreign key references)
func (op *AddTableOp) DependsOn() []model.ObjectKey {
	var deps []model.ObjectKey
	for _, constraint := range op.Table.Constraints {
		if constraint.Type == "foreign_key" && constraint.RefTable != "" {
			deps = append(deps, model.NewObjectKey(constraint.RefSchema, constraint.RefTable, model.KindTable))
		}
	}
	return deps
}

// DropTableOp represents dropping a table
type DropTableOp struct {
	baseOperation
	Schema string
	Name   string
}

// NewDropTableOp creates a new DropTableOp
func NewDropTableOp(schema, name string) *DropTableOp {
	return &DropTableOp{
		baseOperation: baseOperation{
			kind:      KindDropTable,
			objectKey: model.NewObjectKey(schema, name, model.KindTable),
		},
		Schema: schema,
		Name:   name,
	}
}

// RenderString renders the drop table operation as SQL.
func (op *DropTableOp) RenderString(ctx RenderContext) string {
	ifExists := ""
	if ctx.UseIfExists() {
		ifExists = "IF EXISTS "
	}
	return fmt.Sprintf("-- op: drop_table risk:high\nDROP TABLE %s%s;", ifExists, util.QuoteQualifiedIdentifier(op.Schema, op.Name))
}

// IsDestructive returns true for drop table operations
func (op *DropTableOp) IsDestructive() bool {
	return true
}

func renderConstraint(c *model.Constraint) string {
	if c == nil {
		return ""
	}
	definition := renderConstraintDefinition(c)
	if definition == "" {
		return ""
	}
	return fmt.Sprintf("CONSTRAINT %s %s", util.QuoteIdentifier(c.Name), definition)
}

func renderConstraintDefinition(c *model.Constraint) string {
	if c == nil {
		return ""
	}
	switch c.Type {
	case "primary_key":
		return fmt.Sprintf("PRIMARY KEY (%s)", util.QuoteIdentifierList(c.Columns))
	case "foreign_key":
		sql := fmt.Sprintf("FOREIGN KEY (%s) REFERENCES %s (%s)",
			util.QuoteIdentifierList(c.Columns),
			util.QuoteQualifiedIdentifier(c.RefSchema, c.RefTable),
			util.QuoteIdentifierList(c.RefColumns),
		)
		if c.OnDelete != "" {
			sql += fmt.Sprintf(" ON DELETE %s", c.OnDelete)
		}
		if c.OnUpdate != "" {
			sql += fmt.Sprintf(" ON UPDATE %s", c.OnUpdate)
		}
		return sql
	case "unique":
		return fmt.Sprintf("UNIQUE (%s)", util.QuoteIdentifierList(c.Columns))
	case "check":
		if c.Expression != "" {
			return fmt.Sprintf("CHECK (%s)", c.Expression)
		}
		return ""
	}
	if c.Definition != "" {
		return c.Definition
	}
	return ""
}
