package diff

import (
	"fmt"

	"github.com/fred29910/migra-go/internal/model"
	"github.com/fred29910/migra-go/internal/util"
)

type AddColumnOp struct {
	baseOperation
	Schema string
	Table  string
	Column *model.Column
}

func NewAddColumnOp(schema, table string, col *model.Column) *AddColumnOp {
	return &AddColumnOp{
		baseOperation: baseOperation{
			kind:      KindAddColumn,
			objectKey: model.NewObjectKey(schema, table+"."+col.Name, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: col,
	}
}

func (op *AddColumnOp) IsDestructive() bool {
	return false
}

func (op *AddColumnOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

func (op *AddColumnOp) RenderString(ctx RenderContext) string {
	col := op.Column
	sql := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(col.Name), col.DataType)

	if col.IsIdentity {
		switch col.IdentityKind {
		case "ALWAYS":
			sql += " GENERATED ALWAYS AS IDENTITY"
		case "BY DEFAULT":
			sql += " GENERATED BY DEFAULT AS IDENTITY"
		}
	}

	if col.Collation != "" {
		sql += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(col.Collation))
	}
	if !col.IsNullable {
		sql += " NOT NULL"
	}
	if col.DefaultExpr != nil {
		sql += fmt.Sprintf(" DEFAULT %s", *col.DefaultExpr)
	}

	return fmt.Sprintf("-- op: add_column risk:low\n%s;", sql)
}

func (op *AlterColumnTypeOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column), op.ToType)
	if op.UsingExpr != "" {
		sql += " USING " + op.UsingExpr
	}
	return fmt.Sprintf("-- op: alter_column_type risk:high\n%s;", sql)
}

func (op *SetNotNullOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column))
	return fmt.Sprintf("-- op: set_not_null risk:low\n%s;", sql)
}

func (op *DropNotNullOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table), util.QuoteIdentifier(op.Column))
	return fmt.Sprintf("-- op: drop_not_null risk:low\n%s;", sql)
}

func (op *SetDefaultOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: set_default risk:low\nALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.DefaultExpr,
	)
}

func (op *DropDefaultOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_default risk:low\nALTER TABLE %s ALTER COLUMN %s DROP DEFAULT;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

func (op *AlterColumnCollationOp) RenderString(ctx RenderContext) string {
	sql := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DATA TYPE %s",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.DataType,
	)
	if op.ToCollation != "" {
		sql += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(op.ToCollation))
	}
	return fmt.Sprintf("-- op: alter_column_collation risk:low\n%s;", sql)
}

func (op *DropColumnOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_column risk:high\nALTER TABLE %s DROP COLUMN IF EXISTS %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

func (op *AddIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: add_identity risk:low\nALTER TABLE %s ALTER COLUMN %s ADD GENERATED %s AS IDENTITY;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.IdentityKind,
	)
}

func (op *SetIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: set_identity risk:low\nALTER TABLE %s ALTER COLUMN %s SET GENERATED %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
		op.IdentityKind,
	)
}

func (op *DropIdentityOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: drop_identity risk:medium\nALTER TABLE %s ALTER COLUMN %s DROP IDENTITY;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.Column),
	)
}

func (op *RenameColumnOp) RenderString(ctx RenderContext) string {
	return fmt.Sprintf("-- op: rename_column risk:low\nALTER TABLE %s RENAME COLUMN %s TO %s;",
		util.QuoteQualifiedIdentifier(op.Schema, op.Table),
		util.QuoteIdentifier(op.OldName),
		util.QuoteIdentifier(op.NewName),
	)
}

type AlterColumnTypeOp struct {
	baseOperation
	Schema    string
	Table     string
	Column    string
	FromType  string
	ToType    string
	UsingExpr string
}

func NewAlterColumnTypeOp(schema, table, column, fromType, toType string) *AlterColumnTypeOp {
	return &AlterColumnTypeOp{
		baseOperation: baseOperation{
			kind:      KindAlterColumnType,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:   schema,
		Table:    table,
		Column:   column,
		FromType: fromType,
		ToType:   toType,
	}
}

func (op *AlterColumnTypeOp) IsDestructive() bool {
	return true
}

func (op *AlterColumnTypeOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type SetNotNullOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

func NewSetNotNullOp(schema, table, column string) *SetNotNullOp {
	return &SetNotNullOp{
		baseOperation: baseOperation{
			kind:      KindSetNotNull,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

func (op *SetNotNullOp) IsDestructive() bool {
	return false
}

func (op *SetNotNullOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type DropNotNullOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

func NewDropNotNullOp(schema, table, column string) *DropNotNullOp {
	return &DropNotNullOp{
		baseOperation: baseOperation{
			kind:      KindDropNotNull,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

func (op *DropNotNullOp) IsDestructive() bool {
	return false
}

func (op *DropNotNullOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type DropColumnOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

func NewDropColumnOp(schema, table, column string) *DropColumnOp {
	return &DropColumnOp{
		baseOperation: baseOperation{
			kind:      KindDropColumn,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

func (op *DropColumnOp) IsDestructive() bool {
	return true
}

func (op *DropColumnOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type SetDefaultOp struct {
	baseOperation
	Schema      string
	Table       string
	Column      string
	DefaultExpr string
}

func NewSetDefaultOp(schema, table, column, defaultExpr string) *SetDefaultOp {
	return &SetDefaultOp{
		baseOperation: baseOperation{
			kind:      KindSetDefault,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:      schema,
		Table:       table,
		Column:      column,
		DefaultExpr: defaultExpr,
	}
}

func (op *SetDefaultOp) IsDestructive() bool {
	return false
}

func (op *SetDefaultOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type DropDefaultOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

func NewDropDefaultOp(schema, table, column string) *DropDefaultOp {
	return &DropDefaultOp{
		baseOperation: baseOperation{
			kind:      KindDropDefault,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

func (op *DropDefaultOp) IsDestructive() bool {
	return false
}

func (op *DropDefaultOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type SetIdentityOp struct {
	baseOperation
	Schema       string
	Table        string
	Column       string
	IdentityKind string
}

func NewSetIdentityOp(schema, table, column, identityKind string) *SetIdentityOp {
	return &SetIdentityOp{
		baseOperation: baseOperation{
			kind:      KindSetIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:       schema,
		Table:        table,
		Column:       column,
		IdentityKind: identityKind,
	}
}

func (op *SetIdentityOp) IsDestructive() bool {
	return false
}

func (op *SetIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type DropIdentityOp struct {
	baseOperation
	Schema string
	Table  string
	Column string
}

func NewDropIdentityOp(schema, table, column string) *DropIdentityOp {
	return &DropIdentityOp{
		baseOperation: baseOperation{
			kind:      KindDropIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema: schema,
		Table:  table,
		Column: column,
	}
}

func (op *DropIdentityOp) IsDestructive() bool {
	return true
}

func (op *DropIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}

type AddIdentityOp struct {
	baseOperation
	Schema       string
	Table        string
	Column       string
	IdentityKind string
}

func NewAddIdentityOp(schema, table, column, identityKind string) *AddIdentityOp {
	return &AddIdentityOp{
		baseOperation: baseOperation{
			kind:      KindAddIdentity,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:       schema,
		Table:        table,
		Column:       column,
		IdentityKind: identityKind,
	}
}

func (op *AddIdentityOp) IsDestructive() bool { return false }

func (op *AddIdentityOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{model.NewObjectKey(op.Schema, op.Table, model.KindTable)}
}

type AlterColumnCollationOp struct {
	baseOperation
	Schema        string
	Table         string
	Column        string
	DataType      string
	FromCollation string
	ToCollation   string
}

func NewAlterColumnCollationOp(schema, table, column, dataType, fromCollation, toCollation string) *AlterColumnCollationOp {
	return &AlterColumnCollationOp{
		baseOperation: baseOperation{
			kind:      KindAlterColumnCollation,
			objectKey: model.NewObjectKey(schema, table+"."+column, model.KindColumn),
		},
		Schema:        schema,
		Table:         table,
		Column:        column,
		DataType:      dataType,
		FromCollation: fromCollation,
		ToCollation:   toCollation,
	}
}

func (op *AlterColumnCollationOp) IsDestructive() bool {
	return false
}

func (op *AlterColumnCollationOp) DependsOn() []model.ObjectKey {
	return []model.ObjectKey{
		model.NewObjectKey(op.Schema, op.Table, model.KindTable),
	}
}
