package render

import (
	"fmt"
	"strings"

	"github.com/fred29910/migra-go/internal/diff"
	"github.com/fred29910/migra-go/internal/model"
	"github.com/fred29910/migra-go/internal/util"
)

func renderAddTable(r *Renderer, op *diff.AddTableOp) string {
	table := op.Table
	lines := make([]string, 0)

	for _, col := range table.Columns {
		colDef := fmt.Sprintf("    %s %s", util.QuoteIdentifier(col.Name), col.DataType)
		if col.IsIdentity {
			switch col.IdentityKind {
			case "ALWAYS":
				colDef += " GENERATED ALWAYS AS IDENTITY"
			case "BY DEFAULT":
				colDef += " GENERATED BY DEFAULT AS IDENTITY"
			}
		}
		if col.Collation != "" {
			colDef += fmt.Sprintf(" COLLATE %s", util.QuoteIdentifier(col.Collation))
		}
		if !col.IsNullable {
			colDef += " NOT NULL"
		}
		if col.DefaultExpr != nil {
			colDef += fmt.Sprintf(" DEFAULT %s", *col.DefaultExpr)
		}
		lines = append(lines, colDef)
	}

	if table.PrimaryKey != nil {
		pk := &model.Constraint{
			Name:    table.PrimaryKey.Name,
			Type:    "primary_key",
			Columns: table.PrimaryKey.Columns,
		}
		if rendered := renderConstraint(pk); rendered != "" {
			lines = append(lines, "    "+rendered)
		}
	}

	if len(table.Constraints) > 0 {
		names := make([]string, 0, len(table.Constraints))
		for name := range table.Constraints {
			names = append(names, name)
		}
		for _, name := range names {
			c := table.Constraints[name]
			if table.PrimaryKey != nil && c.Name == table.PrimaryKey.Name {
				continue
			}
			if rendered := renderConstraint(c); rendered != "" {
				lines = append(lines, "    "+rendered)
			}
		}
	}

	sql := fmt.Sprintf("-- op: add_table risk:low\nCREATE TABLE %s (\n%s\n);",
		util.QuoteQualifiedIdentifier(table.Schema, table.Name),
		strings.Join(lines, ",\n"))
	return sql
}

func renderDropTable(r *Renderer, op *diff.DropTableOp) string {
	ifExists := ""
	if r.useIfExists {
		ifExists = "IF EXISTS "
	}
	return fmt.Sprintf("-- op: drop_table risk:high\nDROP TABLE %s%s;", ifExists, util.QuoteQualifiedIdentifier(op.Schema, op.Name))
}
